Refactor project structure
Botcrafting/botcraft pull request #16
Opened 2020-09-05 22:24 UTC by thiagomuller

Hey guys, I just refactored project structure to decouple core business code from infra code.
This can be further decoupled, but it's a start;
Please review the code and let me know if you have any suggestions.

2020-09-06 00:08 UTC, rbsilva requested changes
Nice job with the refactor, I liked the interfaces for sending messages and to get books. Just some minor fixes that need to be done before merge:

- Remove the JVM error logs and add them to gitignore. 
- Check the TODO.
 
Suggestions:

- Maybe we could get rid of the mappers and have the telegram inbound classes do the conversion by having toSomething methods, like toUser or toChat, that converts to our core classes.

2020-09-06 00:08 UTC, rbsilva commented on src/main/java/io/botcrafting/botcraft/core/service/handler/HelpCommandProcessor.java
> +	public boolean processMessage(String message) {
is this a working in progress? this TODO will be implemented later?

2020-09-07 01:11 UTC, thiagomuller commented
Hey Rodrigo,
Thanks for reviewing, just removed the log file and put *.log files on gitignore.
The TODO was from another refactor I'm working on right now, but since it's not yet ready, i took away those files for this PR.
Could you kindly review it again?

Thanks!!

2020-09-07 01:43 UTC, rbsilva approved these changes
looks good

2020-09-07 12:59 UTC, merged